from typing import Any


def calculate_health_score(
    features: dict[str, Any]
) -> dict[str, Any]:
    """
    Calculate vehicle health score based on engineered features.

    The score is deterministic and generated by backend logic.
    Gemini only explains this assessment.
    """

    score = 100
    issues = []

    # Mileage assessment
    if features["high_mileage"]:
        score -= 20
        issues.append(
            "Vehicle has high mileage"
        )

    # Service assessment
    if features["service_overdue"]:
        score -= 25
        issues.append(
            "Vehicle service is overdue"
        )

    # Oil assessment
    if features["oil_change_due"]:
        score -= 15
        issues.append(
            "Oil change is due"
        )

    # Brake assessment
    if features["brake_inspection_due"]:
        score -= 20
        issues.append(
            "Brake inspection is recommended"
        )

    # Battery assessment
    if features["battery_check_due"]:
        score -= 10
        issues.append(
            "Battery inspection or replacement may be required"
        )

    # Coolant assessment
    if features["coolant_change_due"]:
        score -= 10
        issues.append(
            "Coolant change is due"
        )

    score = max(score, 0)

    if score >= 80:
        risk_level = "Low"

    elif score >= 50:
        risk_level = "Moderate"

    else:
        risk_level = "High"


    return {
        "health_score": score,
        "risk_level": risk_level,
        "confidence": calculate_confidence(features),
        "issues": issues
    }
    
def calculate_confidence(features: dict) -> str:
    """
    Determine confidence level based on availability of
    vehicle maintenance information.
    """

    missing_information = sum(
        value is None
        for value in [
            features["months_since_service"],
            features["months_since_brake"],
            features["months_since_battery"],
            features["months_since_oil"],
            features["months_since_coolant"],
        ]
    )

    if missing_information == 0:
        return "High"

    elif missing_information <= 2:
        return "Medium"

    else:
        return "Low"