from datetime import datetime
from typing import List, Optional
from enum import Enum

from pydantic import BaseModel, Field


# Component health status model
class ComponentHealth(BaseModel):
    engine_oil: str = Field(
        ...,
        description="Health status of the engine oil."
    )
    brake_pads: str = Field(
        ...,
        description="Health status of the brake pads."
    )
    battery: str = Field(
        ...,
        description="Health status of the battery."
    )
    coolant: str = Field(
        ...,
        description="Health status of the coolant."
    )
    transmission: str = Field(
        ...,
        description="Health status of the transmission."
    )
    tires: str = Field(
        ...,
        description="Health status of the tires."
    )


# Maintenance recommendation model
class MaintenanceRecommendation(BaseModel):
    component: str
    recommendation: str
    priority: str


# AI-generated health assessment
class AIHealthReport(BaseModel):
    """
    Response generated by the AI model.
    Does not contain backend metadata.
    """

    confidence: str = Field(
        ...,
        description="Confidence level of the assessment: High, Medium, or Low."
    )

    health_score: int = Field(
        ...,
        ge=0,
        le=100,
        description="Overall vehicle health score."
    )

    component_health: ComponentHealth

    maintenance_recommendations: List[MaintenanceRecommendation]

    summary: str

class ConfidenceLevel(str, Enum):
    HIGH = "High"
    MEDIUM = "Medium"
    LOW = "Low"
    

# Final API response
class VehicleResponse(BaseModel):
    """
    Complete API response returned to the client.
    Combines backend metadata with AI assessment.
    """

    # Backend-generated metadata
    request_id: str = Field(
        ...,
        description="Unique identifier for this API request."
    )

    generated_at: datetime = Field(
        ...,
        description="Timestamp when the report was generated."
    )

    # AI-generated assessment
    confidence: ConfidenceLevel = Field(
        ...,
        description="Confidence level of the assessment: High, Medium, or Low."
    )

    health_score: int = Field(
        ...,
        ge=0,
        le=100,
        description="Overall vehicle health score."
    )

    component_health: ComponentHealth

    maintenance_recommendations: List[MaintenanceRecommendation]

    summary: str

    # Backend-generated information gaps
    missing_information: Optional[List[str]] = Field(
        default=None,
        description="Additional information that could improve the assessment."
    )